name: mwalimukwawalimu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.7.0
  flutter_vector_icons: ^2.0.0
  motion_tab_bar_v2: ^0.3.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  encrypt: any
  provider: ^6.1.2
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  firebase_messaging: ^15.1.3
  image_picker: ^1.1.2
  http: any
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
